# Generated by Django 4.0.2 on 2022-03-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
