# Generated by Django 4.0.2 on 2022-02-24 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='for_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='for_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='for_superadmin',
            new_name='is_superadmin',
        ),
    ]
